// <auto-generated />
namespace AAExpenseTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class single_tag_alarms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(single_tag_alarms));
        
        string IMigrationMetadata.Id
        {
            get { return "202002062334318_single_tag_alarms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
