// <auto-generated />
namespace AAExpenseTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_queries_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_queries_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202002061636338_added_queries_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
