<%@ Page Title="Add Income" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AddIncome.aspx.cs" Inherits="AAExpenseTracker.AddIncome" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="AddPanel" GroupingText="Log a new Income" runat="server">
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <div class="form-group row">
                    <label for="<%= ConceptTxt.ClientID %>" class="col-md-2 col-form-label">Concept:</label>
                    <div class="col-md-6">
                        <asp:TextBox ID="ConceptTxt" runat="server" CssClass="form-control form-control-sm" placeholder="Concept" required="true"></asp:TextBox>
                    </div>
                    <div class="col-md-4">
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*Required Field" ControlToValidate="ConceptTxt" Display="Dynamic" ForeColor="Red"></asp:RequiredFieldValidator>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label" for="<%=AmntTxt.ClientID %>">Amount:</label>
                    <div class="col-md-6">
                        <asp:TextBox ID="AmntTxt" runat="server" CssClass="form-control form-control-sm" required="true" placeholder="0.00"></asp:TextBox>
                    </div>
                    <div class="col-md-4">
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="*This must be a number" ControlToValidate="AmntTxt" Display="Dynamic" ForeColor="Red" ValidationExpression="^[0-9]+(\.[0-9]{1,2})?"></asp:RegularExpressionValidator>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label" for="<%=DateTxt.ClientID %>">Date:</label>
                    <div class="col-md-6">
                        <asp:TextBox ID="DateTxt" runat="server" CssClass="form-control form-control-sm" TextMode="Date" required="true"></asp:TextBox>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label" for="<%=TagTxt.ClientID %>">Add Tags:</label>
                    <div class="col-md-6">
                        <asp:TextBox ID="TagTxt" CssClass="form-control form-control-sm" placeholder="Multiple tags are separated by commas, i.e. Tag1, Tag2, etc" runat="server"></asp:TextBox>
                    </div>
                </div>
            </ContentTemplate>
            <Triggers>
                <asp:AsyncPostBackTrigger ControlID="AddBtn" EventName="Click" />
            </Triggers>
        </asp:UpdatePanel>
        <div class="form-group row">
            <div class="offset-md-2 col-md-6">
                <asp:Button ID="AddBtn" runat="server" Text="Add" CssClass="btn btn-primary" OnClick="AddBtn_Click" />
            </div>
        </div>
    </asp:Panel>
    <asp:Panel ID="ListPanel" GroupingText="This month's Income" runat="server">
        <asp:UpdatePanel ID="UpdatePanel2" runat="server">
            <ContentTemplate>
                <asp:GridView ID="GridView1" AutoGenerateColumns="False" DataKeyNames="ID" CssClass="table table-bordered table-striped table-sm" GridLines="None" runat="server" AutoGenerateDeleteButton="True" OnDataBinding="GridView1_DataBinding" OnRowDeleting="GridView1_RowDeleting" OnPreRender="Grid_PreRender">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="False" />
                        <asp:BoundField DataField="Concept" HeaderText="Concept" />
                        <asp:BoundField DataField="Amount" DataFormatString="{0:C}" HeaderText="Amount" />
                        <asp:BoundField DataField="Date" DataFormatString="{0:d}" HeaderText="Date" />
                    </Columns>
                    <HeaderStyle CssClass="thead-dark" />
                </asp:GridView>
            </ContentTemplate>
        </asp:UpdatePanel>
    </asp:Panel>
</asp:Content>
